apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-pdf-generator
    team: teamdigihot
  name: hm-pdf-generator
  namespace: teamdigihot
spec:
  image: "{{image}}"
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8082
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 256Mi
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: hm-saksbehandling
        - application: hm-joark-sink
        - application: hm-brev
        - application: hm-joark-sink
