name: Bygg, deploy til dev-gcp og lag release

on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - main
      - distroless

jobs:
  build:
    name: Bygg, deploy til dev-gcp og lag release
    permissions:
      packages: write
      contents: write
      id-token: write
    uses: navikt/hm-workflows/.github/workflows/deploy-dev.yaml@main
    with:
      manifest: .nais/nais-dev.yaml
      java-version: 21
    secrets: inherit
